### ISSUE TITLE
unblock s.youtube.com for core and core - heavy

### ISSUE THREAD

**Issue by QWIILXEY** [SystemJargon/filters#17]
### Which blocklist are you using from this repo?

Core Heavy

### Specify the domain/s or sub-domain/s to allow

s.youtube.com

### Why should the domain/s or sub-domain/s be allowed?

s.youtube.com is needed for watch history to function on youtube

**Comment by SystemJargon** [comment]
This has occurred due to https://github.com/StevenBlack/hosts/issues?q=is%3Aissue+s.youtube.com+ and https://github.com/StevenBlack/hosts/issues/172 which one of my lists sources and aggregates.

My allowlist.txt exclusion should allow s.youtube.com, failing that you would need to add my allowlist which contains the entry you specified.

https://raw.githubusercontent.com/SystemJargon/filters/main/allowlist.txt

or failing that, custom filtering rules like this to your DNS server or adblock syntax solution,

@@||s.youtube.com^$important

**Comment by SystemJargon** [comment]
Your allowlist-request for the domain/subdomain has also been added to https://raw.githubusercontent.com/SystemJargon/filters/main/allowlist/allowlist-request.txt
